version: "3.8"

services:
  express-app:
   container_name: express-app
   # akan di create image dengan nama be:1.0.0 (bkn pull dari docker registry) karena kita define attribute build
   image: be:1.0.0
   # Mendefinsikan dockerfile untuk membuild mage
   build:
    # path dri dockerfile nya
    context: ./
    # nama file dari dockerfile
    dockerfile: Dockerfile
    # Mendifinisikan argument saat build image (--build-arg)
    args: 
     PORT_ARG: 7000
   ports: 
    - protocol: tcp
      published: 5005
      target: 7000